In [1]:
import numpy as np
from scipy.ndimage import binary_dilation

# Binary image A
A = np.array([
    [1, 1, 0, 0, 1, 0, 1],
    [0, 0, 0, 0, 1, 0, 1],
    [1, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 1, 1, 0, 1],
    [1, 0, 1, 0, 0, 1, 1],
    [0, 1, 1, 1, 1, 1, 0],
    [1, 1, 0, 1, 0, 1, 1]
])

# Structuring element B
B = np.array([
    [1],
    [1],
    [1]
])

# Perform dilation
dilated_A = binary_dilation(A, structure=B).astype(int)

# Display the result
print("Original A:")
print(A)
print("\nDilated A:")
print(dilated_A)

Original A:
[[1 1 0 0 1 0 1]
 [0 0 0 0 1 0 1]
 [1 1 0 0 0 0 0]
 [0 0 1 1 1 0 1]
 [1 0 1 0 0 1 1]
 [0 1 1 1 1 1 0]
 [1 1 0 1 0 1 1]]

Dilated A:
[[1 1 0 0 1 0 1]
 [1 1 0 0 1 0 1]
 [1 1 1 1 1 0 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]
